//
export class LocationActions {
}
LocationActions.INIT = "LOCATION_INIT";
//
LocationActions.NEED_PERMS = "LOCATION_NEED_PERMS";
LocationActions.REQUESTPERM = "LOCATION_REQUESTPERM";
LocationActions.PERMS_SUCCESS = "LOCATION_PERMS_SUCCESS";
//
LocationActions.GEOLOCALIZE = "GEOLOCALIZE";
LocationActions.GEOLOCALIZED_SUCCESS = "GEOLOCALIZED_SUCCESS";
LocationActions.GEOLOCALIZED_FAILED = "GEOLOCALIZED_FAILED";
//
LocationActions.SEARCH_ADDRESS = "SEARCH_ADDRESS";
LocationActions.SELECT_ADDRESS = "SELECT_ADDRESS";
LocationActions.FETCHED_SUCCESS = "LOCATION_FETCHED_SUCCESS";
LocationActions.FETCHED_FAILED = "LOCATION_FETCHED_FAILED";
//
LocationActions.CANCEL = "LOCATION_CANCEL";
LocationActions.SUBMIT = "LOCATION_SUBMIT";
LocationActions.SUBMIT_SUCCESS = "LOCATION_SUBMIT_SUCCESS";
//# sourceMappingURL=actions.js.map