/**
 *
 */
export class TRCreateActions {
}
TRCreateActions.CREATE_GOBACK = "CREATE_GOBACK";
TRCreateActions.CREATE_INIT = "CREATE_INIT";
//SUBMIT
TRCreateActions.TRANSACTION_SUBJECT_CHANGED = "TRANSACTION_SUBJECT_CHANGED";
TRCreateActions.TRANSACTION_VALIDATION_CHANGED = "TRANSACTION_VALIDATION_CHANGED";
TRCreateActions.TRANSACTION_CHANGED = "TRANSACTION_CHANGED";
TRCreateActions.TRANSACTION_SUBMIT = "TRANSACTION_SUBMIT";
TRCreateActions.TRANSACTION_SUBMIT_SUCCESS = "TRANSACTION_SUBMIT_SUCCESS";
//EXPIREON
TRCreateActions.START_EXPIREON = "START_EXPIREON";
TRCreateActions.END_EXPIREON = "END_EXPIREON";
//STEPS
TRCreateActions.GOTO_STEP = "GOTO_STEP";
TRCreateActions.STEP_DELETE = "STEP_DELETE";
TRCreateActions.STEP_CHANGED = "STEP_CHANGED";
TRCreateActions.STEP_SUBMIT = "STEP_SUBMIT";
TRCreateActions.STEP_CANCEL = "STEP_CANCEL";
TRCreateActions.STEP_VALID_CHANGED = "STEP_VALID_CHANGED";
TRCreateActions.STEP_SUBMIT_SUCCESS = "STEP_SUBMIT_SUCCESS";
//LOCATION
TRCreateActions.GOTO_LOCATION = "GOTO_LOCATION";
//CONTACTS
TRCreateActions.CONTACT_REMOVE_SUCCESS = "CONTACT_REMOVE_SUCCESS";
TRCreateActions.CONTACT_REMOVE = "CONTACT_REMOVE";
TRCreateActions.GOTO_CONTACT = "GOTO_CONTACT";
TRCreateActions.GOTO_CONTACT_DEST = "GOTO_CONTACT_DEST";
//PHOTOS
TRCreateActions.GOTO_PHOTO = "GOTO_PHOTO";
TRCreateActions.PHOTO_NEED_PERMS = "PHOTO_NEED_PERMS";
TRCreateActions.PHOTO_REQUESTPERM = "PHOTOREQUESTPERM";
TRCreateActions.PHOTO_PERMS_SUCCESS = "PHOTO_PERMS_SUCCESS";
TRCreateActions.PHOTO_PICKED_BEGIN = "PHOTO_PICKED_BEGIN";
TRCreateActions.PHOTO_PICKED_SUCCESS = "PHOTO_PICKED_SUCCESS";
TRCreateActions.PHOTO_REMOVE = "PHOTO_REMOVE";
TRCreateActions.PHOTO_CANCEL = "PHOTO_CANCEL";
TRCreateActions.PHOTO_SOURCE = "PHOTO_SOURCE";
//# sourceMappingURL=create.js.map