/**
 *
 */
export class TRListActions {
}
//FETCH
TRListActions.FETCH_DATA_PENDING = "FETCH_DATA_PENDING";
TRListActions.FETCH_DATA_FAIL = "FETCH_DATA_FAIL";
TRListActions.FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
//DETAIL
TRListActions.GOTO_DETAIL = "GOTO_DETAIL";
TRListActions.DETAIL_LOADING = "DETAIL_LOADING";
TRListActions.DETAIL_LOAD_SUCCESS = "DETAIL_LOAD_SUCCESS";
TRListActions.DETAIL_FINISH = "DETAIL_FINISH";
TRListActions.DETAIL_CANCEL = "DETAIL_CANCEL";
TRListActions.DETAIL_CANCEL_SUCCESS = "DETAIL_CANCEL_SUCCESS";
TRListActions.DETAIL_GOBACK = "DETAIL_GOBACK";
//SEARCH
TRListActions.SEARCH_START = "SEARCH_START";
TRListActions.SEARCH_START_SUCCESS = "SEARCH_START_SUCCESS";
TRListActions.SEARCH_CHANGE = "SEARCH_CHANGE";
TRListActions.SEARCH_STOP = "SEARCH_STOP";
TRListActions.SEARCH_STOP_SUCCESS = "SEARCH_STOP_SUCCESS";
//ACTIONS
TRListActions.TRANSACTION_FINISH = "TRANSACTION_FINISH";
TRListActions.TRANSACTION_CANCEL = "TRANSACTION_CANCEL";
//# sourceMappingURL=list.js.map