export default class Action {
}
Action.SIGNIN_NEED_PHONE = "SIGNIN_NEED_PHONE";
Action.SIGNIN_PHONE_SUBMIT = "SIGNIN_PHONE_SUBMIT";
Action.SIGNIN_PHONE_SUBMIT_ERROR = "SIGNIN_PHONE_SUBMIT_ERROR";
Action.SIGNIN_NEED_CODE = "SIGNIN_NEED_CODE";
Action.SIGNIN_CODE_SUBMIT = "SIGNIN_CODE_SUBMIT";
Action.SIGNIN_CODE_SUBMIT_ERROR = "SIGNIN_CODE_SUBMIT_ERROR";
Action.FETCH_USER_PENDING = "FETCH_USER_PENDING";
Action.FETCH_USER_FAIL = "FETCH_USER_FAIL";
Action.FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
Action.UPDATE_USER = "UPDATE_USER";
Action.UPDATE_PENDING = "UPDATE_PENDING";
Action.UPDATE_SUCCESS = "UPDATE_SUCCESS";
Action.UPDATE_FAIL = "UPDATE_FAIL";
//# sourceMappingURL=actions.js.map