# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pretemprunt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pretemprunt
  pod 'Firebase/Core'

  target 'pretempruntTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'pretemprunt-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pretemprunt-tvOS

  target 'pretemprunt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
