/**
 *
 */
export class ContactActions {
}
// 
ContactActions.INIT = "CONTACT_INIT";
//PERMS
ContactActions.NEED_PERMS = "CONTACT_NEED_PERMS";
ContactActions.PERMS_SUCCESS = "CONTACT_PERMS_SUCCESS";
ContactActions.REQUESTPERM_CONTACT = "CONTACT_REQUESTPERM_CONTACT";
//FETCH
ContactActions.FETCH = "CONTACT_FETCH";
ContactActions.FETCHED_SUCCESS = "CONTACT_FETCHED_SUCCESS";
ContactActions.FETCHED_FAILED = "CONTACT_FETCHED_FAILED";
//ACTIONS
ContactActions.TOGGLE = "CONTACT_TOGGLE";
ContactActions.CANCEL = "CONTACT_CANCEL";
ContactActions.SUBMIT = "CONTACT_SUBMIT";
ContactActions.SUBMIT_SUCCESS = "CONTACT_SUBMIT_SUCCESS";
//SEARCH
ContactActions.SEARCH_START = "CONTACT_SEARCH_START";
ContactActions.SEARCH_START_SUCCESS = "CONTACT_SEARCH_START_SUCCESS";
ContactActions.SEARCH_CHANGE = "CONTACT_SEARCH_CHANGE";
ContactActions.SEARCH_STOP = "CONTACT_SEARCH_STOP";
ContactActions.SEARCH_STOP_SUCCESS = "CONTACT_SEARCH_STOP_SUCCESS";
//# sourceMappingURL=actions.js.map